RTOP=../../../
MODULE=server
SUBDIRS=

CXXSOURCES=command.cc context.cc log.cc master.cc meta.cc meta-test.cc \
	return.cc session.cc token.cc worker.cc
OUTPUT=lib

ifndef TOP
include $(RTOP)/bs/Make.local
endif
