RTOP=../../../
MODULE=commands
SUBDIRS=

CXXSOURCES=authenticate.cc compress.cc deleteacl.cc deletedsince.cc \
	freecontext.cc getquota.cc listrights.cc logout.cc myrights.cc noop.cc \
	path.cc search.cc setacl.cc sleep.cc starttls.cc store.cc \
	sync-sleep.cc updatecontext.cc

ifndef TOP
include $(RTOP)/bs/Make.local
endif
