RTOP=../../../
MODULE=datastore
SUBDIRS=

CXXSOURCES=acl.cc attribute.cc authz.cc comparator.cc constants.cc \
	criteria.cc dataset.cc datastore.cc entry.cc exceptions.cc \
	modtime.cc notify-sink.cc notify-source.cc path.cc sort.cc \
	subcontext.cc transaction.cc trans-logger.cc xml-dump.cc \
	xml-loader.cc
OUTPUT=lib

ifndef TOP
include $(RTOP)/bs/Make.local
endif
